version: "3"

services:
  jupyter:
    image: jupyter/minimal-notebook:latest
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/home/jovyan/workspace

volumes:
  jupyter-jovyan:
