version: "3"

services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
    volumes:
      - jupyter-jovyan:/home/jovyan
      - .:/home/jovyan/work

volumes:
  jupyter-jovyan:
